### ISSUE TITLE
Why does my plug-in not work?

### ISSUE THREAD

**Issue by lovelyJason** [EnlighterJS/Plugin.WordPress#174] opened 2019-06-26 10:06 UTC
It has only 'pre' labels,and It has not button,why?

**Comment by AndiDittrich** [comment] 2019-06-26 10:11
Hi @lovelyJason 

please provide more detailed information...

**Comment by lovelyJason** [comment] 2019-06-26 10:28
I have seen your website 'enlighterjs.org'.And I saw the correct structure should be like this:
<div class="EnlighterJSWrapper enlighterEnlighterJSWrapper">
  <ol class="hoverEnabled enlighterEnlighterJS EnlighterJS">
    <li class=" odd"><span class="">Element</span><span class="sy0">.</span><span class="me0">implement</span><span
        class="br0">(</span><span class="br0">{</span><span class=""></span></li>
    <li class=" even"><span class=""> </span><span class="co2">/**</span></li>
    <li class=" odd"><span class="co2"> * Highlights an element/Removes Element highlighting</span></li>
    <li class=" even"><span class="co2"> *</span></li>

  </ol>
  <pre style="display: none;">

    code
  </pre>
  <div class="EnlighterJSToolbar"><a class="EnlighterJSInfoButton" title="EnlighterJS Syntax Highlighter"></a><a
      class="EnlighterJSRawButton" title="Toggle RAW Code"></a><a class="EnlighterJSWindowButton"
      title="Open Code in new Window"></a><span class="clear"></span></div>
</div>

But,my web is such a structure :
<pre class="EnlighterJSRAW" data-enlighter-language="js">
    code
</pre>

so it can't work.but in the past,it can be work correctly.why?

**Comment by lovelyJason** [comment] 2019-06-26 10:29
"<div class="EnlighterJSWrapper enlighterEnlighterJSWrapper">
  <ol class="hoverEnabled enlighterEnlighterJS EnlighterJS">
    <li class=" odd"><span class="">Element</span><span class="sy0">.</span><span class="me0">implement</span><span
        class="br0">(</span><span class="br0">{</span><span class=""></span></li>
    <li class=" even"><span class=""> </span><span class="co2">/**</span></li>
    <li class=" odd"><span class="co2"> * Highlights an element/Removes Element highlighting</span></li>
    <li class=" even"><span class="co2"> *</span></li>

  </ol>
  <pre style="display: none;">

    code
  </pre>
  <div class="EnlighterJSToolbar"><a class="EnlighterJSInfoButton" title="EnlighterJS Syntax Highlighter"></a><a
      class="EnlighterJSRawButton" title="Toggle RAW Code"></a><a class="EnlighterJSWindowButton"
      title="Open Code in new Window"></a><span class="clear"></span></div>
</div>"

my: 
"<pre class="EnlighterJSRAW" data-enlighter-language="js">code</pre>"

**Comment by lovelyJason** [comment] 2019-06-26 10:31
I'm sorry, I can't write the ''pre" label here,so can you understand my problem

**Comment by lovelyJason** [comment] 2019-06-26 10:33
`<div class="EnlighterJSWrapper enlighterEnlighterJSWrapper">
  <ol class="hoverEnabled enlighterEnlighterJS EnlighterJS">
    <li class=" odd"><span class="">Element</span><span class="sy0">.</span><span class="me0">implement</span><span
        class="br0">(</span><span class="br0">{</span><span class=""></span></li>
    <li class=" even"><span class=""> </span><span class="co2">/**</span></li>
    <li class=" odd"><span class="co2"> * Highlights an element/Removes Element highlighting</span></li>
    <li class=" even"><span class="co2"> *</span></li>

  </ol>
  <pre style="display: none;">

    code
  </pre>
  <div class="EnlighterJSToolbar"><a class="EnlighterJSInfoButton" title="EnlighterJS Syntax Highlighter"></a><a
      class="EnlighterJSRawButton" title="Toggle RAW Code"></a><a class="EnlighterJSWindowButton"
      title="Open Code in new Window"></a><span class="clear"></span></div>
</div>`

and mine:

`<pre class="EnlighterJSRAW" data-enlighter-language="js">
       code
</pre>`

**Comment by lovelyJason** [comment] 2019-06-26 10:34
`<div class="EnlighterJSWrapper enlighterEnlighterJSWrapper">
  <ol class="hoverEnabled enlighterEnlighterJS EnlighterJS">
    <li class=" odd"><span class="">Element</span><span class="sy0">.</span><span class="me0">implement</span><span
        class="br0">(</span><span class="br0">{</span><span class=""></span></li>
    <li class=" even"><span class=""> </span><span class="co2">/**</span></li>
    <li class=" odd"><span class="co2"> * Highlights an element/Removes Element highlighting</span></li>
    <li class=" even"><span class="co2"> *</span></li>

  </ol>
  <pre style="display: none;">

    code
  </pre>
  <div class="EnlighterJSToolbar"><a class="EnlighterJSInfoButton" title="EnlighterJS Syntax Highlighter"></a><a
      class="EnlighterJSRawButton" title="Toggle RAW Code"></a><a class="EnlighterJSWindowButton"
      title="Open Code in new Window"></a><span class="clear"></span></div>
</div>`

and mine:

`<pre class="EnlighterJSRAW" data-enlighter-language="js">
       code
</pre>`

**Comment by lovelyJason** [comment] 2019-06-26 10:36
I have seen your website 'enlighterjs.org'.And I saw the correct structure should be like that,but mine is diffrent, I want to know how to resolve this problem.thanks

**Comment by AndiDittrich** [comment] 2019-06-26 10:37
@lovelyJason 

please use 3 backticks to open + close a codeblock - see [GFM cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code)

the structure is correct! EnlighterJS transforms the `<pre>` tag to the html code you've posted above - that is the intended behavior

**Comment by lovelyJason** [comment] 2019-06-26 10:48
but my EnlighterJS  plugin  cant work properly.it has not  three buttons include 'Toggle RAW Code','Open Code in new Window' and 'EnlighterJS Syntax Highlighter ' in the upper right corner.And, when I use EnlighterJS   in wordpress Backstage,and it's generated structures like this: `<pre class="EnlighterJSRAW" data-enlighter-language="js">
       code
</pre>`.this will not be enough.

**Comment by AndiDittrich** [comment] 2019-06-26 10:56
@lovelyJason 

please provide a link to your blog - i cannot help you with such useless information....

everything you posted is the expected behavior - it seems that the frontend resources (EnlighterJS library, MooTools framework) are missing. maybe due to some kind of caching plugin like autoptimize or wp-supercache...

the html structures created by the editing plugins **are correct**

**Comment by lovelyJason** [comment] 2019-06-26 10:59
Thank you! I think 'pre' label should be wrapped in 'div' and  display correctly,isn't it? And my blog is 'http://www.sanshao.top/css3.html' .Please help me see what's the problem.I'm sorry to bother you.

**Comment by AndiDittrich** [comment] 2019-06-26 11:10
the `<pre>` tag is used as kind of "marker" ... it just contains the code which should be highlighted and is set to invisible in case EnlighterJS takes the element.

your website has a serious issue: the themes footer is not loaded (no closing html/body tags, no scripts) - believe there is an internal server error thrown on each page call...please check your php/webserver errorlogs

=> therefore the EnlighterJS resources (library + MooTools + init code) framework are missing as well as all theme scripts

**Comment by lovelyJason** [comment] 2019-06-26 12:00
Thank you for your help.I finally solved my problem.You areright,I have no closing body tags

**Closed** 2019-06-26 12:01 UTC
Labels: question
