### ISSUE TITLE
toolbar settings not working

### ISSUE THREAD

**Issue by Vivarsh** [EnlighterJS/Plugin.WordPress#330] opened 2021-04-06 04:32 UTC
Toolbar settings are not working. After making changes to the toolbar settings, the changes are getting saved for admin only. If I log out of admin, the toolbar is visible on the code with default settings. For example, if I hide the toolbar and then log out of admin, I will see the toolbar on the code.

**Comment by AndiDittrich** [comment] 2021-04-06 09:29
sounds like an active cache/optimization plugin - don't forget to clear caches after applying changes

**Comment by Vivarsh** [comment] 2021-05-06 14:30
Sorry for the late update. Thanks for the solution, it worked. I am facing another issue now. The code indentation doesn't look properly on mobile and even on browsers except for the chrome browser (only on desktop). Refer to the below screenshots for more clarity:

On Chrome:
![image](https://user-images.githubusercontent.com/63698543/117315715-922a1380-aea5-11eb-9a98-13dc3295b0b9.png)

On other browsers and mobile:
![image](https://user-images.githubusercontent.com/63698543/117315778-a110c600-aea5-11eb-850c-e9e5c6593550.png)

**Comment by AndiDittrich** [comment] 2021-05-06 14:33
do you use tabs or whitespaces as indentation ?

**Comment by Vivarsh** [comment] 2021-05-06 14:42
yes. whitespaces.

**Comment by Vivarsh** [comment] 2021-05-20 05:19
any update?

**Comment by AndiDittrich** [comment] 2021-05-20 07:47
seems to be a css issue - since i'm unable to reproduce it i would assume that it's caused by your template. if you can provide a link i'll take a short look onto

**Comment by Vivarsh** [comment] 2021-05-22 01:45
I had applied additional css and i think after that only the issue began. But i have removed the css now, cleared cache, but the issue still remains. you can check this link https://hiberstack.com/ansible-playbook-example/

**Comment by AndiDittrich** [comment] 2021-05-22 12:12
it's not an Enlighter issue... you're using some kind of optimization/minification plugin which strips leading whitespaces from the html

**Comment by Vivarsh** [comment] 2021-05-27 20:42
ok thanks for the update

**Comment by AndiDittrich** [comment] 2021-07-03 18:59
any updates ? otherwise i'll close the issue since it's not Enlighter related

**Comment by Vivarsh** [comment] 2021-07-05 04:56
No thanks. We can close the issue

**Closed** 2021-07-05 04:56 UTC
