### ISSUE TITLE
Some visual errors in latest stable Enlighter.v4

### ISSUE THREAD

**Issue by arash88** [EnlighterJS/Plugin.WordPress#242] opened 2020-04-16 13:29 UTC
Hi dear Andy,
I've come across some visual errors after updating to latest stable v4 branch from official Wordpress repo. Please consider below screenshot:

1- In RAW mode there is a couple of extra tabs before lines begins; which wasn't there in the previous version and kinda looks bad.

2- I can't hide info button("E") from toolbar anymore.

3- Toolbar is very ill-placed inside single row blocks.

![enlighter](https://user-images.githubusercontent.com/13942180/79461629-ac2f5480-800b-11ea-8b6e-729ec3245ccf.jpg)

**Comment by AndiDittrich** [comment] 2020-04-16 13:40
Hi @arash88 ,

thanks for your feedback.

1. it is the intended behaviour: by switching to raw code (with enabled line numbering) the padding is retained to avoid "flipping" of the codeblock. you can override this with custom css

2. you can remove the button manually via custom css, `v4.1` may include an option to hide it but i'm currently not sure if this is a good solution.

3. EnlighterJS is not designed for single lines of code - use the inline mode instead or disable the toolbar

**Comment by AndiDittrich** [comment] 2020-04-16 17:58
v4.1 has been released including an option to disable the attribution button

**Closed** 2020-04-17 08:40 UTC
Labels: question
