### ISSUE TITLE
Warning with lang attribute in shortcode : Illegal string offset 'lang'

### ISSUE THREAD

**Issue by julien-jacob** [EnlighterJS/Plugin.WordPress#226] opened 2020-02-23 14:10 UTC
Hello ! 

I have this warning when I use a shortcode like : [enlighter lang="javascript"]alert('hello');[/enlighter]

``` 
Warning: Illegal string offset 'lang' in /wp-content/plugins/enlighter/class/ShortcodeFilter.php on line 84
``` 

I fix it with change : 

``` 
if ($attb['lang']) {
``` 

by 

```
if (isset($attb['lang'])) {
``` 
In /wp-content/plugins/enlighter/class/ShortcodeFilter.php on line 84
And no Warnig after :) 
I use a bad shortcode syntax ? 

Best regards

**Comment by AndiDittrich** [comment] 2020-02-23 14:16
Dear @julien-jacob 

thanks for your report. i've to investigate the issue - the error code sounds weird since the `$attb` variable should be an array not a string. maybe it's a compatibility issue with the current wordpress release or php .

btw. shortcodes are deprecated and **should not used anymore** - take a look on the full visual editor integration

br, Andi

**Comment by AndiDittrich** [comment] 2020-02-23 21:51
fixed within the master branch. it is only raised in case the generic enlighter shortcode is used **without attributes**

it is caused by `shortcode_parse_atts` which returns a string instead of an empty array in case no attributes were found (great wp api consistency.....)

however, thanks for your report!

**Closed** 2020-02-23 21:51 UTC
Labels: Bug, status/validated
