### ISSUE TITLE
CSS Line-Numbering alters Code Identation

### ISSUE THREAD

**Issue by crossi36** [EnlighterJS/Plugin.WordPress#57] opened 2017-01-14 14:10 UTC
Wordpress Version: 4.7.1
PHP Version: 7.0.12

Enlighter Plugin Version: 3.3
EnlighterJS Version: 2.10.1
Theme: Minimal (with customised colours)
Language: Python

![example](https://cloud.githubusercontent.com/assets/12022001/21955421/398834c2-da6b-11e6-87cb-797e91d0849e.jpeg)

**Comment by AndiDittrich** [comment] 2017-01-14 15:02
thx. could you please post a minimal example of the code you've tried to insert ?

**Comment by crossi36** [comment] 2017-01-14 15:26
I've tried different code snippets, the problem seems to be independent from the actual code one wishes to display. Anyway, here is a code snippet that is long enough for the problem:
```
import numpy as np

def feedBackward(self, outputs, labels):
    deltas = []
    e = (outputs[-1][0] - labels).transpose()
    delta = np.multiply(outputs[-1][1].transpose(), e)
    for i in range(len(self.Ws)-1, -1,-1):
        W = self.Ws[i][1:,:]
        deltas.append(delta)
        delta = np.multiply(outputs[i][1].transpose(), W * delta)	
    deltas.append(delta)
    return list(reversed(deltas))
```

**Comment by AndiDittrich** [comment] 2017-01-15 12:08
with the snippet above i cannot reproduce your issue. there is no indentation which could removed by the "Insert Dialog". the import as well as def statement are on position 0. 

i believe your issue has another origin.

is the indentation/left-padding only visible in your frontend and not in the visual editor ? if so it seems to be an issue with your WordPress theme. Maybe margin/padding added to Enlighter's `div` or `ul/li` container - try to inspect the element

**Comment by crossi36** [comment] 2017-01-15 12:39
In the post editor everything looks fine. However, in the frontend the code isn't aligned when the line number goes from single to double digit (presumably also when it goes from double to triple digit). I've noticed the same behaviour on [your homepage](https://andidittrich.de/2016/04/allow-authors-and-contributors-to-use-special-html-attributes-in-wordpress.html).

<img width="480" src="https://cloud.githubusercontent.com/assets/12022001/21962445/8a7e434c-db26-11e6-9146-dc3bc7f82a36.png">

Removing the list-style with the inspect tool in Chrome removes the problem, but the line numbers aren't shown anymore. Using `decimal-leading-zero inside` instead of `decimal inside` also fixes the alignment error.

**Comment by AndiDittrich** [comment] 2017-01-15 14:14
oh ok, now i undestand the issue :)

of course, it is caused by the css list styles. it will be fixed in EnlighterJS v3 but not in the current release.

**Closed** 2018-07-15 09:32 UTC
Labels: Bug, EnlighterJS, EnlighterJS v3
