### ISSUE TITLE
JetPack Plugin: markdown codeblocks not highlighted

### ISSUE THREAD

**Issue by parthi2929** [EnlighterJS/Plugin.WordPress#97] opened 2018-04-18 12:31 UTC
Hi

I have visual editor disabled and markdown enabled in my WP jet pack. I tried using your plugin in markdown mode (enabled in editing tab) but nothing works. 

Currently I use Codecolorer. I tried disabling that and check, but same result. Can you please check? 

Below is the page suffering: 
https://www.rparthiban.com/articles/misc/test-pad/

**Comment by AndiDittrich** [comment] 2018-04-18 13:03
Hi parthi2929,

you have to disable the code highlighting of JetPack markdown - otherwise Enlighter cannot work because the elements are taken over by JetPack.

br, Andi

**Comment by parthi2929** [comment] 2018-04-18 15:06
Hi

How do we do that? Also you can see in above page, codecolorer which is another plugin, works fine.

**Comment by AndiDittrich** [comment] 2018-04-18 15:08
i will investigate the issue, i'm not sure how the other plugins are working

**Comment by parthi2929** [comment] 2018-04-18 15:15
Thank you. This might be because their shortcode is different? yours using same as markdown's?

**Comment by AndiDittrich** [comment] 2018-04-18 15:16
as mentioned in the contextual-help: only GFM-style fenced codeblocks are supported

**Comment by AndiDittrich** [comment] 2018-04-18 19:17
there is an incompatibility in between JetPacks markdown parser and Enlighter 
**which cannot be fixed without changing the JetPack plugin**

the JetPack plugin is designed to convert markdown to html each time the post is saved. this has the advantage that your content which is written in markdown is still available as pure html in case you disable the plugin. Enlighter in the opposite applies the markdown filter when the content is requested by the template - it didn't touch the content by design. therefore the JetPack markdown fenced codeblock processing is always taken precedence.

as a simple workaround you can use the Enlighter shortcodes instead of fenced codeblocks because the JetPack markown plugin keeps them untouched.

generally i recommend to use another markdown plugin because the JetPack ones is not very configurable.

best regards, Andi

**Comment by AndiDittrich** [comment] 2018-04-22 15:28
@parthi2929

i've just added a "compatibility mode" to Enlighter (v3.6-BETA3) which converts legacy highlighting code (e.g. created by Jetpack markdown) into Enlighter codeblocks on-the-fly.

this should address the issue

**Comment by AndiDittrich** [comment] 2018-05-20 12:15
available in v3.6 - have fun :)

**Closed by AndiDittrich** 2018-05-20 12:15 UTC
Labels: 3rd Party Issue, Bug

**Comment by cbernet** [comment] 2019-01-09 17:31
Hello, I'm sorry to revive this issue, but for me the compatibility mode does not work. 
I'm using jetpack markdown (would you like to suggest any other markdown editor? I don't mind changing), and enlighter 3.8.1.

I wrote the following in a jetpack markdown block, and I don't get syntax highlighting (cannot give you the raw code here, but you see that the fenced code block is correct from the syntax highlighting on github)

```python
def func(a):
  return a

for i in range(10):
  print i
```

<img width="868" alt="image" src="https://user-images.githubusercontent.com/4138171/50916639-e2128000-143b-11e9-8fa7-5b1d5cd0209c.png">

Many thanks for your help.

**Comment by AndiDittrich** [comment] 2019-01-09 17:42
@cbernet 

i didn't test the compatibility mode with Gutenberg JetPack Markdown because there is the "Enlighter Sourcecode" block available (Full Gutenberg Editor Integration) which works flawlessly. 

Using a markdown block with embedded sourcecode is a very weak workaround...do you really want to use it this way ?

**Comment by cbernet** [comment] 2019-01-09 18:12
@AndiDittrich thanks for the fast answer! Maybe the enlighter sourcecode block would fit my needs. But where can i find it? When editing a post, if i click on the little + sign at the top left to add a block, it's not there. 

My goal is to write my posts fully in markdown, and to get syntax highlighting when I use fenced code blocks in the post, like on github for example. I'm certainly willing to try a different markdown editor that jetpack. Do you know of a good one that works well for enlighter? 

Sorry my answers and questions probably sound naive but I started my first blog yesterday and I'm just getting started with wordpress :)

**Comment by AndiDittrich** [comment] 2019-01-09 19:55
for the moment, use the "Text Editor" (`User -> Your Profile Disable the visual editor when writing`) or the Classic Editor (formerly the WordPress visual edtor/tinymce) when writing in JetPack markdown.

personally i use my custom markdown plugin which is not released

**Comment by cbernet** [comment] 2019-01-10 16:40
Hi @AndiDittrich, thanks a lot, it's working now!
